/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.cardiffmet.st20131041.ui;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Dries Janse
 */
public class OptionPanel extends javax.swing.JPanel {

    private final Color defaultPanelColor = new Color(119,171,89);
    private final Color defaultHoverPanelColor = new Color(201,223,138);
    private final Color defaultClickedPanelColor = new Color(54,128,45);
    private String labelText = "Label text";
    private ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("uk/ac/cardiffmet/st20131041/resources/add-contacts.png"));
    
    /**
     * Creates new form OptionPanel
     */
    public OptionPanel() {
        //this.icon = new ImageIcon(getClass().getClassLoader().getResource("uk/ac/cardiffmet/st20131041/resources/add-contacts.png"));
        createIcon("uk/ac/cardiffmet/st20131041/resources/add-contacts.png");
        initComponents();
    }

    public OptionPanel(String labelText, String path){
        this.setLabelText(labelText);
        this.createIcon(path);
        this.initComponents();
    }
    
    public void setDefaultColor(){
        this.setBackground(this.defaultPanelColor);
    }
    
    public void setDefaultHoverColor(){
        this.setBackground(this.defaultHoverPanelColor);
    }
    
    public void setDefaultClickedPanelColor(){
        this.setBackground(this.defaultClickedPanelColor);
    }    
    
    public String getLabelText() {
        return labelText;
    }

    public void setLabelText(String labelText) {
        this.labelText = labelText;
    }

    public ImageIcon getIcon() {
        return icon;
    }

    public void setIcon(ImageIcon icon) {
        this.icon = icon;
    }
    
    private void createIcon(String path){
        this.setIcon(new ImageIcon(getClass().getClassLoader().getResource(path)));
    }

    public Color getDefaultPanelColor() {
        return defaultPanelColor;
    }

    public Color getDefaultHoverPanelColor() {
        return defaultHoverPanelColor;
    }

    public Color getDefaultClickedPanelColor() {
        return defaultClickedPanelColor;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addEventIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(119, 171, 89));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText(this.getLabelText());

        addEventIcon.setIcon(this.getIcon());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(addEventIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(addEventIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEventIcon;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
